[2022-01-25 11:24:11,473] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T11:12:24.583418+00:00 [queued]>
[2022-01-25 11:24:11,720] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T11:12:24.583418+00:00 [queued]>
[2022-01-25 11:24:11,723] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:24:11,746] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2022-01-25 11:24:11,762] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:24:11,916] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T11:12:24.583418+00:00
[2022-01-25 11:24:11,938] {standard_task_runner.py:52} INFO - Started process 8196 to run task
[2022-01-25 11:24:11,977] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T11:12:24.583418+00:00', '--job-id', '130', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpoazp_oxh', '--error-file', '/tmp/tmpq_n1a1bn']
[2022-01-25 11:24:12,001] {standard_task_runner.py:77} INFO - Job 130: Subtask apply_model
[2022-01-25 11:24:12,825] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T11:12:24.583418+00:00 [running]> on host 54a54d544bf0
[2022-01-25 11:24:12,977] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T11:12:24.583418+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T11:12:24.583418+00:00
[2022-01-25 11:24:19,110] {taskinstance.py:1455} ERROR - [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_630.jpeg' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_630.jpeg'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 116, in apply_dl_model
    os.rename(process_dir+"/"+filename,process_dir+"/"+prediction_label +filename)
OSError: [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_630.jpeg' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_630.jpeg'
[2022-01-25 11:24:19,147] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=classification, task_id=apply_model, execution_date=20220125T111224, start_date=20220125T112411, end_date=20220125T112419
[2022-01-25 11:24:19,222] {local_task_job.py:146} INFO - Task exited with return code 1
