[2022-01-25 10:21:27,677] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.save_result 2022-01-25T10:20:47.998539+00:00 [queued]>
[2022-01-25 10:21:27,728] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.save_result 2022-01-25T10:20:47.998539+00:00 [queued]>
[2022-01-25 10:21:27,730] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:21:27,731] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 10:21:27,731] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:21:27,783] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_result> on 2022-01-25T10:20:47.998539+00:00
[2022-01-25 10:21:27,802] {standard_task_runner.py:52} INFO - Started process 8876 to run task
[2022-01-25 10:21:27,831] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'save_result', '2022-01-25T10:20:47.998539+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpjmzwmg2j', '--error-file', '/tmp/tmpehnx6fzk']
[2022-01-25 10:21:27,851] {standard_task_runner.py:77} INFO - Job 62: Subtask save_result
[2022-01-25 10:21:28,086] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.save_result 2022-01-25T10:20:47.998539+00:00 [running]> on host 2dc98551bc76
[2022-01-25 10:21:28,267] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=save_result
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T10:20:47.998539+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-25T10:20:47.998539+00:00
[2022-01-25 10:21:28,273] {logging_mixin.py:104} INFO - hello
[2022-01-25 10:21:28,282] {taskinstance.py:1455} ERROR - too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 121, in save_result
    predict_label,img=tuple(filename.split("_"))
ValueError: too many values to unpack (expected 2)
[2022-01-25 10:21:28,316] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=classification, task_id=save_result, execution_date=20220125T102047, start_date=20220125T102127, end_date=20220125T102128
[2022-01-25 10:21:28,445] {local_task_job.py:146} INFO - Task exited with return code 1
