[2022-01-25 10:26:40,584] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T10:21:10.257136+00:00 [queued]>
[2022-01-25 10:26:40,603] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T10:21:10.257136+00:00 [queued]>
[2022-01-25 10:26:40,604] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:26:40,604] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 10:26:40,604] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:26:40,630] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T10:21:10.257136+00:00
[2022-01-25 10:26:40,638] {standard_task_runner.py:52} INFO - Started process 12839 to run task
[2022-01-25 10:26:40,645] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T10:21:10.257136+00:00', '--job-id', '70', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpol080pbk', '--error-file', '/tmp/tmp7dtaopq5']
[2022-01-25 10:26:40,651] {standard_task_runner.py:77} INFO - Job 70: Subtask apply_model
[2022-01-25 10:26:40,712] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T10:21:10.257136+00:00 [running]> on host 2dc98551bc76
[2022-01-25 10:26:40,768] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T10:21:10.257136+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T10:21:10.257136+00:00
[2022-01-25 10:27:20,231] {taskinstance.py:1455} ERROR - image file is truncated (106 bytes not processed)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 104, in apply_dl_model
    img = image.load_img(os.path.join(process_dir,filename), target_size=(64, 64))
  File "/usr/local/lib/python3.6/site-packages/keras/preprocessing/image.py", line 314, in load_img
    target_size=target_size, interpolation=interpolation)
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 138, in load_img
    img = img.resize(width_height_tuple, resample)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1989, in resize
    self.load()
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    "image file is truncated "
OSError: image file is truncated (106 bytes not processed)
[2022-01-25 10:27:20,291] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=classification, task_id=apply_model, execution_date=20220125T102110, start_date=20220125T102640, end_date=20220125T102720
[2022-01-25 10:27:20,495] {local_task_job.py:146} INFO - Task exited with return code 1
