[2022-01-25 10:43:50,006] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:43:37.985759+00:00 [queued]>
[2022-01-25 10:43:50,035] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:43:37.985759+00:00 [queued]>
[2022-01-25 10:43:50,035] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:43:50,036] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 10:43:50,036] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:43:50,054] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): bing_image_download> on 2022-01-25T10:43:37.985759+00:00
[2022-01-25 10:43:50,062] {standard_task_runner.py:52} INFO - Started process 4879 to run task
[2022-01-25 10:43:50,069] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bing_image_download', 'bing_image_download', '2022-01-25T10:43:37.985759+00:00', '--job-id', '92', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bing_image_download.py', '--cfg-path', '/tmp/tmpgfz9ha1d', '--error-file', '/tmp/tmporxut1cf']
[2022-01-25 10:43:50,070] {standard_task_runner.py:77} INFO - Job 92: Subtask bing_image_download
[2022-01-25 10:43:50,130] {logging_mixin.py:104} INFO - Running <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:43:37.985759+00:00 [running]> on host 327d6291ad28
[2022-01-25 10:43:50,209] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bing_image_download
AIRFLOW_CTX_TASK_ID=bing_image_download
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T10:43:37.985759+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-25T10:43:37.985759+00:00
[2022-01-25 10:43:50,217] {logging_mixin.py:104} INFO - [INFO] searching Bing API for 'pikachu'
[2022-01-25 10:44:00,235] {taskinstance.py:1455} ERROR - HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=0&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f07c8f240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5f07c8f240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=0&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f07c8f240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bing_image_download.py", line 83, in bing_image_download
    search = requests.get(URL, headers=headers, params=params)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=0&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f07c8f240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
[2022-01-25 10:44:00,244] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=bing_image_download, task_id=bing_image_download, execution_date=20220125T104337, start_date=20220125T104350, end_date=20220125T104400
[2022-01-25 10:44:00,290] {local_task_job.py:146} INFO - Task exited with return code 1
