[2022-01-25 13:48:45,164] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T13:45:41.648219+00:00 [queued]>
[2022-01-25 13:48:45,185] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T13:45:41.648219+00:00 [queued]>
[2022-01-25 13:48:45,185] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 13:48:45,186] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2022-01-25 13:48:45,186] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 13:48:45,204] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T13:45:41.648219+00:00
[2022-01-25 13:48:45,213] {standard_task_runner.py:52} INFO - Started process 578 to run task
[2022-01-25 13:48:45,218] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T13:45:41.648219+00:00', '--job-id', '163', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmphl_nj1m7', '--error-file', '/tmp/tmpxq2nkm2j']
[2022-01-25 13:48:45,224] {standard_task_runner.py:77} INFO - Job 163: Subtask apply_model
[2022-01-25 13:48:45,282] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T13:45:41.648219+00:00 [running]> on host 05cddda723d4
[2022-01-25 13:48:45,379] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T13:45:41.648219+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-25T13:45:41.648219+00:00
[2022-01-25 13:48:51,968] {taskinstance.py:1455} ERROR - [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 116, in apply_dl_model
    os.rename(process_dir+"/"+filename,process_dir+"/"+prediction_label +filename)
OSError: [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png'
[2022-01-25 13:48:51,975] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=classification, task_id=apply_model, execution_date=20220125T134541, start_date=20220125T134845, end_date=20220125T134851
[2022-01-25 13:48:52,036] {local_task_job.py:146} INFO - Task exited with return code 1
