[2022-01-25 11:34:05,388] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T11:27:24.583418+00:00 [queued]>
[2022-01-25 11:34:05,492] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T11:27:24.583418+00:00 [queued]>
[2022-01-25 11:34:05,493] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:34:05,493] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 11:34:05,494] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:34:05,531] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T11:27:24.583418+00:00
[2022-01-25 11:34:05,544] {standard_task_runner.py:52} INFO - Started process 8340 to run task
[2022-01-25 11:34:05,558] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T11:27:24.583418+00:00', '--job-id', '140', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpee8kr005', '--error-file', '/tmp/tmpf6x_xv03']
[2022-01-25 11:34:05,567] {standard_task_runner.py:77} INFO - Job 140: Subtask apply_model
[2022-01-25 11:34:05,704] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T11:27:24.583418+00:00 [running]> on host 54a54d544bf0
[2022-01-25 11:34:05,829] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T11:27:24.583418+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T11:27:24.583418+00:00
[2022-01-25 11:34:09,632] {taskinstance.py:1455} ERROR - [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 116, in apply_dl_model
    os.rename(process_dir+"/"+filename,process_dir+"/"+prediction_label +filename)
OSError: [Errno 36] File name too long: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_629.png'
[2022-01-25 11:34:09,670] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=classification, task_id=apply_model, execution_date=20220125T112724, start_date=20220125T113405, end_date=20220125T113409
[2022-01-25 11:34:09,787] {local_task_job.py:146} INFO - Task exited with return code 1
