[2021-12-24 11:54:46,561] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2021-12-24T11:42:50.453196+00:00 [queued]>
[2021-12-24 11:54:46,637] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2021-12-24T11:42:50.453196+00:00 [queued]>
[2021-12-24 11:54:46,639] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-24 11:54:46,639] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-12-24 11:54:46,640] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-24 11:54:46,713] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2021-12-24T11:42:50.453196+00:00
[2021-12-24 11:54:46,747] {standard_task_runner.py:52} INFO - Started process 1054 to run task
[2021-12-24 11:54:46,777] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2021-12-24T11:42:50.453196+00:00', '--job-id', '162', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmp3_g11c8i', '--error-file', '/tmp/tmpp3rvzu6c']
[2021-12-24 11:54:46,797] {standard_task_runner.py:77} INFO - Job 162: Subtask apply_model
[2021-12-24 11:54:47,041] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2021-12-24T11:42:50.453196+00:00 [running]> on host 0d76f33c6135
[2021-12-24 11:54:47,173] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2021-12-24T11:42:50.453196+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-24T11:42:50.453196+00:00
[2021-12-24 11:55:03,386] {logging_mixin.py:104} WARNING - /usr/local/lib/python3.6/site-packages/PIL/Image.py:976 UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
[2021-12-24 11:55:30,472] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_pikachu_134.jpeg' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_pikachu_134.jpeg'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 116, in apply_dl_model
    os.rename(process_dir+"/"+filename,process_dir+"/"+prediction_label +filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_pikachu_134.jpeg' -> '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_pikachu_134.jpeg'
[2021-12-24 11:55:30,687] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=classification, task_id=apply_model, execution_date=20211224T114250, start_date=20211224T115446, end_date=20211224T115530
[2021-12-24 11:55:31,266] {local_task_job.py:146} INFO - Task exited with return code 1
