[2022-01-25 10:53:11,985] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:47:58.250907+00:00 [queued]>
[2022-01-25 10:53:12,017] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:47:58.250907+00:00 [queued]>
[2022-01-25 10:53:12,018] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:53:12,019] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 10:53:12,019] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 10:53:12,093] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): bing_image_download> on 2022-01-25T10:47:58.250907+00:00
[2022-01-25 10:53:12,106] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2022-01-25 10:53:12,117] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bing_image_download', 'bing_image_download', '2022-01-25T10:47:58.250907+00:00', '--job-id', '96', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bing_image_download.py', '--cfg-path', '/tmp/tmpoi3ygewu', '--error-file', '/tmp/tmpzjm8r30a']
[2022-01-25 10:53:12,118] {standard_task_runner.py:77} INFO - Job 96: Subtask bing_image_download
[2022-01-25 10:53:12,259] {logging_mixin.py:104} INFO - Running <TaskInstance: bing_image_download.bing_image_download 2022-01-25T10:47:58.250907+00:00 [running]> on host 54a54d544bf0
[2022-01-25 10:53:12,356] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bing_image_download
AIRFLOW_CTX_TASK_ID=bing_image_download
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T10:47:58.250907+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T10:47:58.250907+00:00
[2022-01-25 10:53:12,364] {logging_mixin.py:104} INFO - [INFO] searching Bing API for 'pikachu'
[2022-01-25 10:53:19,342] {logging_mixin.py:104} INFO - [INFO] 1000 total results for 'pikachu'
[2022-01-25 10:53:19,347] {logging_mixin.py:104} INFO - [INFO] making request for group 0-50 of 1000...
[2022-01-25 10:53:22,234] {logging_mixin.py:104} INFO - [INFO] saving images for group 0-50 of 1000...
[2022-01-25 10:53:22,235] {logging_mixin.py:104} INFO - [INFO] fetching: http://vignette3.wikia.nocookie.net/wii/images/7/77/Pikachu_SSB4.jpg/revision/latest?cb=20140210000421
[2022-01-25 10:53:37,472] {logging_mixin.py:104} INFO - [INFO] fetching: https://pngimg.com/uploads/pokemon/pokemon_PNG15.png
[2022-01-25 10:53:42,573] {logging_mixin.py:104} INFO - [INFO] fetching: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4f6bf5b3-c9b6-44c2-ab80-06e3ea80d511/dca37p4-e992703b-3518-475a-a3bd-bc2831f13e7b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNGY2YmY1YjMtYzliNi00NGMyLWFiODAtMDZlM2VhODBkNTExXC9kY2EzN3A0LWU5OTI3MDNiLTM1MTgtNDc1YS1hM2JkLWJjMjgzMWYxM2U3Yi5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.BgM4bC-lqNizie8fhV-EnS5hLNCPn5y8iROlzXNAdk4
[2022-01-25 10:53:49,202] {logging_mixin.py:104} INFO - [INFO] fetching: https://pngimg.com/uploads/pokemon/pokemon_PNG93.png
[2022-01-25 10:53:50,128] {logging_mixin.py:104} INFO - [INFO] fetching: https://pngimg.com/uploads/pokemon/pokemon_PNG148.png
[2022-01-25 10:53:52,972] {logging_mixin.py:104} INFO - [INFO] fetching: https://3.bp.blogspot.com/-QRBqlfFJt6U/ULpgGND3XFI/AAAAAAAACPs/TUrUig9gj5A/s1600/pikachu.png
[2022-01-25 10:54:06,482] {logging_mixin.py:104} INFO - [INFO] fetching: https://www.nintendoworldreport.com/media/38183/4/1.jpg
[2022-01-25 10:54:13,878] {logging_mixin.py:104} INFO - [INFO] fetching: https://ph.portal-pokemon.com/upload/en/HelloPika.png
[2022-01-25 10:54:23,889] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='ph.portal-pokemon.com', port=443): Max retries exceeded with url: /upload/en/HelloPika.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef257f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
[2022-01-25 10:54:23,893] {logging_mixin.py:104} INFO - [INFO] fetching: https://pngimg.com/uploads/pokemon/pokemon_PNG42.png
[2022-01-25 10:54:32,998] {logging_mixin.py:104} INFO - [INFO] fetching: https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/91cc6c40961423.5793b50987cac.jpg
[2022-01-25 10:54:48,346] {logging_mixin.py:104} INFO - [INFO] fetching: http://clipartmag.com/image/pikachu-images-for-drawing-29.png
[2022-01-25 10:54:58,350] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='clipartmag.com', port=80): Max retries exceeded with url: /image/pikachu-images-for-drawing-29.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
[2022-01-25 10:54:58,356] {logging_mixin.py:104} INFO - [INFO] fetching: https://yt3.ggpht.com/a-/AAuE7mBRlOG3moYW1oLN4L0V6FP-O-3IJrF1NoGjDw=s900-mo-c-c0xffffffff-rj-k-no
[2022-01-25 10:55:08,370] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='yt3.ggpht.com', port=443): Max retries exceeded with url: /a-/AAuE7mBRlOG3moYW1oLN4L0V6FP-O-3IJrF1NoGjDw=s900-mo-c-c0xffffffff-rj-k-no (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80048>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
[2022-01-25 10:55:08,448] {logging_mixin.py:104} INFO - [INFO] fetching: https://cdn.vox-cdn.com/thumbor/RGPwZaA8xxwrVd4spVyTGNrxHh0=/99x0:1179x720/1200x800/filters:focal(99x0:1179x720)/cdn.vox-cdn.com/uploads/chorus_image/image/50166993/2016.1_Great_Detective_Pikachu_Birth_of_a_New_Duo__3DS_.0.0.jpg
[2022-01-25 10:55:13,576] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='cdn.vox-cdn.com', port=443): Max retries exceeded with url: /thumbor/RGPwZaA8xxwrVd4spVyTGNrxHh0=/99x0:1179x720/1200x800/filters:focal(99x0:1179x720)/cdn.vox-cdn.com/uploads/chorus_image/image/50166993/2016.1_Great_Detective_Pikachu_Birth_of_a_New_Duo__3DS_.0.0.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,577] {logging_mixin.py:104} INFO - [INFO] fetching: https://cdn.myminifactory.com/assets/object-assets/5c64403a9c7ad/images/d27029fa-5bce-4731-b8b4-af6be07fe701.jpg
[2022-01-25 10:55:13,591] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='cdn.myminifactory.com', port=443): Max retries exceeded with url: /assets/object-assets/5c64403a9c7ad/images/d27029fa-5bce-4731-b8b4-af6be07fe701.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,593] {logging_mixin.py:104} INFO - [INFO] fetching: https://img1.cgtrader.com/items/2419585/aef1cf6064/pikachu-pokemon-3d-printing-3d-model-obj-stl-blend.jpg
[2022-01-25 10:55:13,608] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='img1.cgtrader.com', port=443): Max retries exceeded with url: /items/2419585/aef1cf6064/pikachu-pokemon-3d-printing-3d-model-obj-stl-blend.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,609] {logging_mixin.py:104} INFO - [INFO] fetching: https://mir-s3-cdn-cf.behance.net/project_modules/1400/56f6e170109017.5d71da93da213.png
[2022-01-25 10:55:13,621] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='mir-s3-cdn-cf.behance.net', port=443): Max retries exceeded with url: /project_modules/1400/56f6e170109017.5d71da93da213.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,638] {logging_mixin.py:104} INFO - [INFO] fetching: https://graffitiscuba.com/wp-content/uploads/2018/03/Cartoons10.jpg
[2022-01-25 10:55:13,646] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='graffitiscuba.com', port=443): Max retries exceeded with url: /wp-content/uploads/2018/03/Cartoons10.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,647] {logging_mixin.py:104} INFO - [INFO] fetching: https://pngimg.com/uploads/pokemon/pokemon_PNG102.png
[2022-01-25 10:55:13,655] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='pngimg.com', port=443): Max retries exceeded with url: /uploads/pokemon/pokemon_PNG102.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,655] {logging_mixin.py:104} INFO - [INFO] fetching: https://cdn.mos.cms.futurecdn.net/dqW4eWEXeU6J8tBpZTpqy5.jpg
[2022-01-25 10:55:13,664] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='cdn.mos.cms.futurecdn.net', port=443): Max retries exceeded with url: /dqW4eWEXeU6J8tBpZTpqy5.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,665] {logging_mixin.py:104} INFO - [INFO] fetching: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c5bbbf70-cfca-4aeb-892b-6ac8c54fb175/ddbr84t-d0753923-bc99-4919-8bb6-2121149399d7.png/v1/fill/w_956,h_836,strp/pikachu_libre_render_by_vexikku_ddbr84t-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzUwMCIsInBhdGgiOiJcL2ZcL2M1YmJiZjcwLWNmY2EtNGFlYi04OTJiLTZhYzhjNTRmYjE3NVwvZGRicjg0dC1kMDc1MzkyMy1iYzk5LTQ5MTktOGJiNi0yMTIxMTQ5Mzk5ZDcucG5nIiwid2lkdGgiOiI8PTQwMDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.SCZGQ24m5GxrmvuwHJ6Em8lOGDWKTpacKjSjkkFMbCs
[2022-01-25 10:55:13,673] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com', port=443): Max retries exceeded with url: /f/c5bbbf70-cfca-4aeb-892b-6ac8c54fb175/ddbr84t-d0753923-bc99-4919-8bb6-2121149399d7.png/v1/fill/w_956,h_836,strp/pikachu_libre_render_by_vexikku_ddbr84t-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzUwMCIsInBhdGgiOiJcL2ZcL2M1YmJiZjcwLWNmY2EtNGFlYi04OTJiLTZhYzhjNTRmYjE3NVwvZGRicjg0dC1kMDc1MzkyMy1iYzk5LTQ5MTktOGJiNi0yMTIxMTQ5Mzk5ZDcucG5nIiwid2lkdGgiOiI8PTQwMDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.SCZGQ24m5GxrmvuwHJ6Em8lOGDWKTpacKjSjkkFMbCs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,674] {logging_mixin.py:104} INFO - [INFO] fetching: http://img2.wikia.nocookie.net/__cb20110811011944/pokemonfanon/images/8/88/Pikachu_XXV.PNG
[2022-01-25 10:55:13,681] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='img2.wikia.nocookie.net', port=80): Max retries exceeded with url: /__cb20110811011944/pokemonfanon/images/8/88/Pikachu_XXV.PNG (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,682] {logging_mixin.py:104} INFO - [INFO] fetching: https://static3.srcdn.com/wordpress/wp-content/uploads/2020/10/Pokemon-Sword-and-Shield-Ash-Ketchum-Pikachu.jpg
[2022-01-25 10:55:13,689] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='static3.srcdn.com', port=443): Max retries exceeded with url: /wordpress/wp-content/uploads/2020/10/Pokemon-Sword-and-Shield-Ash-Ketchum-Pikachu.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,689] {logging_mixin.py:104} INFO - [INFO] fetching: http://cdn.shopify.com/s/files/1/0284/4907/9395/products/sticker_pikachu.jpg?v=1573513085
[2022-01-25 10:55:13,696] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='cdn.shopify.com', port=80): Max retries exceeded with url: /s/files/1/0284/4907/9395/products/sticker_pikachu.jpg?v=1573513085 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdeedbda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,697] {logging_mixin.py:104} INFO - [INFO] fetching: https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/12/Pikachu-Feature-Image-Cropped.jpg
[2022-01-25 10:55:13,704] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='static1.cbrimages.com', port=443): Max retries exceeded with url: /wordpress/wp-content/uploads/2019/12/Pikachu-Feature-Image-Cropped.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbf98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,704] {logging_mixin.py:104} INFO - [INFO] fetching: https://preview.redd.it/x2wdfznl7dc31.jpg?auto=webp&s=ac11d594b10cd85ecdce3c3850887649d6ca7da6
[2022-01-25 10:55:13,712] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='preview.redd.it', port=443): Max retries exceeded with url: /x2wdfznl7dc31.jpg?auto=webp&s=ac11d594b10cd85ecdce3c3850887649d6ca7da6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbf98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,713] {logging_mixin.py:104} INFO - [INFO] fetching: https://i2.wp.com/metro.co.uk/wp-content/uploads/2016/06/ash_s_pikachu-0.png?quality=90&strip=all&zoom=1&resize=899%2C580&ssl=1
[2022-01-25 10:55:13,721] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='i2.wp.com', port=443): Max retries exceeded with url: /metro.co.uk/wp-content/uploads/2016/06/ash_s_pikachu-0.png?quality=90&strip=all&zoom=1&resize=899%2C580&ssl=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,722] {logging_mixin.py:104} INFO - [INFO] fetching: https://graphictide.com/images/shop/hover/307_pikachu-candy.png
[2022-01-25 10:55:13,729] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='graphictide.com', port=443): Max retries exceeded with url: /images/shop/hover/307_pikachu-candy.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,730] {logging_mixin.py:104} INFO - [INFO] fetching: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/25247b92-6844-4fef-8ed8-5055cc35bf58/dd18tmd-d30941e9-a135-4565-ba5f-ac90be835d62.png/v1/fill/w_958,h_834,strp/pikachu_run_render_by_nintega_dario_dd18tmd-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTc1MCIsInBhdGgiOiJcL2ZcLzI1MjQ3YjkyLTY4NDQtNGZlZi04ZWQ4LTUwNTVjYzM1YmY1OFwvZGQxOHRtZC1kMzA5NDFlOS1hMTM1LTQ1NjUtYmE1Zi1hYzkwYmU4MzVkNjIucG5nIiwid2lkdGgiOiI8PTIwMTAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.pq9b6WZU8vHbWtw8DC3WwZi3p6WYzSD7f0YKTUaru2g
[2022-01-25 10:55:13,739] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com', port=443): Max retries exceeded with url: /f/25247b92-6844-4fef-8ed8-5055cc35bf58/dd18tmd-d30941e9-a135-4565-ba5f-ac90be835d62.png/v1/fill/w_958,h_834,strp/pikachu_run_render_by_nintega_dario_dd18tmd-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTc1MCIsInBhdGgiOiJcL2ZcLzI1MjQ3YjkyLTY4NDQtNGZlZi04ZWQ4LTUwNTVjYzM1YmY1OFwvZGQxOHRtZC1kMzA5NDFlOS1hMTM1LTQ1NjUtYmE1Zi1hYzkwYmU4MzVkNjIucG5nIiwid2lkdGgiOiI8PTIwMTAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.pq9b6WZU8vHbWtw8DC3WwZi3p6WYzSD7f0YKTUaru2g (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,739] {logging_mixin.py:104} INFO - [INFO] fetching: http://tonsoffacts.com/wp-content/uploads/2019/11/fp4716-pokemon-pikachu-glow.jpg
[2022-01-25 10:55:13,746] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='tonsoffacts.com', port=80): Max retries exceeded with url: /wp-content/uploads/2019/11/fp4716-pokemon-pikachu-glow.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,747] {logging_mixin.py:104} INFO - [INFO] fetching: http://images4.fanpop.com/image/photos/22200000/Pikachu-pikachu-22265985-1280-1120.jpg
[2022-01-25 10:55:13,754] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='images4.fanpop.com', port=80): Max retries exceeded with url: /image/photos/22200000/Pikachu-pikachu-22265985-1280-1120.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,754] {logging_mixin.py:104} INFO - [INFO] fetching: https://img.huffingtonpost.com/asset/5a10b3b0180000aa09f6ce35.jpeg?ops=1910_1000
[2022-01-25 10:55:13,762] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='img.huffingtonpost.com', port=443): Max retries exceeded with url: /asset/5a10b3b0180000aa09f6ce35.jpeg?ops=1910_1000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef800b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,763] {logging_mixin.py:104} INFO - [INFO] fetching: https://animetos.com/wp-content/uploads/2021/03/img_8458-scaled.jpeg
[2022-01-25 10:55:13,769] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='animetos.com', port=443): Max retries exceeded with url: /wp-content/uploads/2021/03/img_8458-scaled.jpeg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,770] {logging_mixin.py:104} INFO - [INFO] fetching: https://www.onlinetoys.com.au/19664/pokemon-power-action-pikachu.jpg
[2022-01-25 10:55:13,777] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='www.onlinetoys.com.au', port=443): Max retries exceeded with url: /19664/pokemon-power-action-pikachu.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,777] {logging_mixin.py:104} INFO - [INFO] fetching: http://1.bp.blogspot.com/-abBmZroOWLE/VI1OaUQRSVI/AAAAAAAAHag/BUaUVdHh1Ak/s1600/Pikachu_Vector.png
[2022-01-25 10:55:13,784] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='1.bp.blogspot.com', port=80): Max retries exceeded with url: /-abBmZroOWLE/VI1OaUQRSVI/AAAAAAAAHag/BUaUVdHh1Ak/s1600/Pikachu_Vector.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,784] {logging_mixin.py:104} INFO - [INFO] fetching: https://s3.us-east-1.amazonaws.com/dexerto-assets-production-cbbdf288/uploads/2020/02/16230146/pokemon-community-fat-pikachu-meme.jpg
[2022-01-25 10:55:13,792] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='s3.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /dexerto-assets-production-cbbdf288/uploads/2020/02/16230146/pokemon-community-fat-pikachu-meme.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,792] {logging_mixin.py:104} INFO - [INFO] fetching: https://cdn.weasyl.com/~tsaoshin/submissions/1351357/26480474c4f1b1f6b42aa02c67540a21a3daa4cf4da375229ccf723d56d1377d/tsaoshin-025-pikachu.png
[2022-01-25 10:55:13,799] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='cdn.weasyl.com', port=443): Max retries exceeded with url: /~tsaoshin/submissions/1351357/26480474c4f1b1f6b42aa02c67540a21a3daa4cf4da375229ccf723d56d1377d/tsaoshin-025-pikachu.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,800] {logging_mixin.py:104} INFO - [INFO] fetching: https://yt3.ggpht.com/a/AATXAJwmhNbZwsDbo_tXP-d9wB7tSqNpV56GFvSjhQ=s900-c-k-c0xffffffff-no-rj-mo
[2022-01-25 10:55:13,807] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='yt3.ggpht.com', port=443): Max retries exceeded with url: /a/AATXAJwmhNbZwsDbo_tXP-d9wB7tSqNpV56GFvSjhQ=s900-c-k-c0xffffffff-no-rj-mo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,807] {logging_mixin.py:104} INFO - [INFO] fetching: https://yt3.ggpht.com/a/AATXAJw9Y95jJiDSFXIG6GWfIZKdHbgfovkOcj66BA=s900-c-k-c0xffffffff-no-rj-mo
[2022-01-25 10:55:13,815] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='yt3.ggpht.com', port=443): Max retries exceeded with url: /a/AATXAJw9Y95jJiDSFXIG6GWfIZKdHbgfovkOcj66BA=s900-c-k-c0xffffffff-no-rj-mo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,816] {logging_mixin.py:104} INFO - [INFO] fetching: https://img2.cgtrader.com/items/670200/bb4720355b/pikachu-3d-model-low-poly-obj-c4d-stl-ztl-mtl.png
[2022-01-25 10:55:13,823] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='img2.cgtrader.com', port=443): Max retries exceeded with url: /items/670200/bb4720355b/pikachu-3d-model-low-poly-obj-c4d-stl-ztl-mtl.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,823] {logging_mixin.py:104} INFO - [INFO] fetching: https://cdn.gamer-network.net/2018/usgamer/Detective-Pikachu-Header-03.jpg/EG11/thumbnail/1920x1080/format/jpg/quality/75/detective-pikachu-pokemon-next-generation-switch-impressions.jpg
[2022-01-25 10:55:13,830] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='cdn.gamer-network.net', port=443): Max retries exceeded with url: /2018/usgamer/Detective-Pikachu-Header-03.jpg/EG11/thumbnail/1920x1080/format/jpg/quality/75/detective-pikachu-pokemon-next-generation-switch-impressions.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,831] {logging_mixin.py:104} INFO - [INFO] fetching: https://img2.cgtrader.com/items/768075/a6212ac1a3/pokemon-pikachu-3d-model-low-poly-rigged.jpg
[2022-01-25 10:55:13,838] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='img2.cgtrader.com', port=443): Max retries exceeded with url: /items/768075/a6212ac1a3/pokemon-pikachu-3d-model-low-poly-rigged.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,838] {logging_mixin.py:104} INFO - [INFO] fetching: https://preview.redd.it/r3r5fzcibmh21.jpg?auto=webp&s=fb5f20934cc89940c787d04a9a324b7fbed1cb34
[2022-01-25 10:55:13,845] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='preview.redd.it', port=443): Max retries exceeded with url: /r3r5fzcibmh21.jpg?auto=webp&s=fb5f20934cc89940c787d04a9a324b7fbed1cb34 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbeb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,846] {logging_mixin.py:104} INFO - [INFO] fetching: https://soyummy.com/wp-content/uploads/2018/11/pikachu.jpg
[2022-01-25 10:55:13,853] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='soyummy.com', port=443): Max retries exceeded with url: /wp-content/uploads/2018/11/pikachu.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,853] {logging_mixin.py:104} INFO - [INFO] fetching: https://static2.thegamerimages.com/wordpress/wp-content/uploads/2019/05/Detective-Pikachu-4.jpg
[2022-01-25 10:55:13,860] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='static2.thegamerimages.com', port=443): Max retries exceeded with url: /wordpress/wp-content/uploads/2019/05/Detective-Pikachu-4.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbf28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,861] {logging_mixin.py:104} INFO - [INFO] fetching: http://www.baltana.com/files/wallpapers-14/Pikachu-Widescreen-Wallpapers-37659.jpg
[2022-01-25 10:55:13,868] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='www.baltana.com', port=80): Max retries exceeded with url: /files/wallpapers-14/Pikachu-Widescreen-Wallpapers-37659.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdeedbf60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,869] {logging_mixin.py:104} INFO - [INFO] fetching: https://webgames.host/uploads/2018/03/pikachu-bros.png
[2022-01-25 10:55:13,876] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='webgames.host', port=443): Max retries exceeded with url: /uploads/2018/03/pikachu-bros.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdeedbf28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,876] {logging_mixin.py:104} INFO - [INFO] fetching: https://vignette3.wikia.nocookie.net/pokemon/images/6/64/Spikey_Eared_Pichu.jpg/revision/latest/scale-to-width-down/2000?cb=20130129204810
[2022-01-25 10:55:13,884] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='vignette3.wikia.nocookie.net', port=443): Max retries exceeded with url: /pokemon/images/6/64/Spikey_Eared_Pichu.jpg/revision/latest/scale-to-width-down/2000?cb=20130129204810 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,885] {logging_mixin.py:104} INFO - [INFO] fetching: http://oyster.ignimgs.com/mediawiki/apis.ign.com/pokken-tournament/b/b0/Detail-pikachu.png
[2022-01-25 10:55:13,896] {logging_mixin.py:104} INFO - [ERROR]:  HTTPConnectionPool(host='oyster.ignimgs.com', port=80): Max retries exceeded with url: /mediawiki/apis.ign.com/pokken-tournament/b/b0/Detail-pikachu.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cdef80cf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,897] {logging_mixin.py:104} INFO - [INFO] fetching: https://s3.us-east-1.amazonaws.com/dexerto-assets-production-cbbdf288/uploads/2020/08/26080403/ashs-pikachu-on-verge-of-evolving-pokemon-journeys-23-years-franchise-icon.jpg
[2022-01-25 10:55:13,906] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='s3.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /dexerto-assets-production-cbbdf288/uploads/2020/08/26080403/ashs-pikachu-on-verge-of-evolving-pokemon-journeys-23-years-franchise-icon.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,907] {logging_mixin.py:104} INFO - [INFO] fetching: https://brokenpanda.net/wp-content/uploads/1588943949_865_Pikachu-HD-Wallpapers-2020.jpg
[2022-01-25 10:55:13,918] {logging_mixin.py:104} INFO - [ERROR]:  HTTPSConnectionPool(host='brokenpanda.net', port=443): Max retries exceeded with url: /wp-content/uploads/1588943949_865_Pikachu-HD-Wallpapers-2020.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:13,947] {logging_mixin.py:104} INFO - [INFO] making request for group 50-100 of 1000...
[2022-01-25 10:55:14,004] {taskinstance.py:1455} ERROR - HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=50&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=50&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bing_image_download.py", line 102, in bing_image_download
    search = requests.get(URL, headers=headers, params=params)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.bing.microsoft.com', port=443): Max retries exceeded with url: /v7.0/images/search/?q=pikachu&offset=50&count=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5cdef80cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[2022-01-25 10:55:14,054] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=bing_image_download, task_id=bing_image_download, execution_date=20220125T104758, start_date=20220125T105311, end_date=20220125T105514
[2022-01-25 10:55:14,238] {local_task_job.py:146} INFO - Task exited with return code 1
