[2022-01-25 11:04:58,831] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T10:57:24.583418+00:00 [queued]>
[2022-01-25 11:04:58,901] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2022-01-25T10:57:24.583418+00:00 [queued]>
[2022-01-25 11:04:58,902] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:04:58,903] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-01-25 11:04:58,903] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 11:04:58,955] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2022-01-25T10:57:24.583418+00:00
[2022-01-25 11:04:58,973] {standard_task_runner.py:52} INFO - Started process 12690 to run task
[2022-01-25 11:04:58,992] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2022-01-25T10:57:24.583418+00:00', '--job-id', '110', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpzj6feype', '--error-file', '/tmp/tmp1z6err5y']
[2022-01-25 11:04:59,002] {standard_task_runner.py:77} INFO - Job 110: Subtask apply_model
[2022-01-25 11:04:59,135] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2022-01-25T10:57:24.583418+00:00 [running]> on host 54a54d544bf0
[2022-01-25 11:04:59,255] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T10:57:24.583418+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T10:57:24.583418+00:00
[2022-01-25 11:06:32,154] {logging_mixin.py:104} WARNING - /usr/local/lib/python3.6/site-packages/PIL/Image.py:976 UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
[2022-01-25 11:06:36,784] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_654.jpeg'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 104, in apply_dl_model
    img = image.load_img(os.path.join(process_dir,filename), target_size=(64, 64))
  File "/usr/local/lib/python3.6/site-packages/keras/preprocessing/image.py", line 314, in load_img
    target_size=target_size, interpolation=interpolation)
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 113, in load_img
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/process_dir/bulbasaur_bulbasaur_bulbasaur_bulbasaur_pikachu_654.jpeg'
[2022-01-25 11:06:36,790] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=classification, task_id=apply_model, execution_date=20220125T105724, start_date=20220125T110458, end_date=20220125T110636
[2022-01-25 11:06:36,826] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2022-01-25 11:06:36,831] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 12690
[2022-01-25 11:06:36,846] {process_utils.py:66} INFO - Process psutil.Process(pid=12690, status='terminated', exitcode=1, started='11:04:58') (12690) terminated with exit code 1
